name: Fetch issue activity

on:
  schedule:
    - cron: "15 4 * * *"
  workflow_dispatch:

jobs:
  fetch-comments:
    runs-on: ubuntu-latest
    env:
      ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      INACTIVE_APP_ID: ${{ secrets.INACTIVE_APP_ID }}
      INACTIVE_CLIENT_ID: ${{ secrets.INACTIVE_CLIENT_ID }}
      INACTIVE_CLIENT_SECRET: ${{ secrets.INACTIVE_CLIENT_SECRET }}
      INACTIVE_PRIVATE_KEY: ${{ secrets.INACTIVE_PRIVATE_KEY }}
      OUTFILE: /tmp/db.json
    steps:
      - uses: actions/checkout@v2
        with:
          path: master
      - uses: actions/checkout@v2
        with:
          ref: activity
          path: activity
      - name: Stage db.json
        run: mv ${{ github.workspace }}/activity/db.json ${{ github.workspace }}/master/db.json
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ github.workspace }}/master
      - name: Collect Comments
        run: node src/issues.js && mv db.json $OUTFILE
        working-directory: ${{ github.workspace }}/master
      - name: Update db.json
        run: |
          rm -rf db.json
          mv $OUTFILE ./db.json
          git config --global user.name "github-actions[bot]"
          git config --global user.email "YOUR_BOT_EMAIL"
          git add db.json
          git commit -m 'adding latest issue comments'
          git push
        working-directory: ${{ github.workspace }}/activity
